version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-web
    working_dir: /var/www/html
    volumes:
      - ./html/:/var/www/html
    environment:
      - TZ=Asia/Taipei
    depends_on:
      - db
    ports:
      - "80:80"
  db:
    image: mysql:5.7
    container_name: message-db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      TZ: Asia/Taipei
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
